[env:d1_mini]
platform = espressif8266 @ ~4.2.1
board = d1_mini
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    -D BEARSSL_SSL_BASIC

lib_deps =
    olikraus/U8g2 @ ^2.35.7
    paulstoffregen/Encoder @ ^1.4.4
    me-no-dev/ESPAsyncTCP @ ^1.2.2
    https://github.com/esphome/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.4
